package embedgen

import (
	"bytes"
	"fmt"
	"go/format"
	"path/filepath"
	"strings"

	"github.com/duxweb/runa/view"
)

// Config describes one generated embed file.
type Config struct {
	Name     string
	Root     string
	Patterns []string
	Package  string
}

// Generate returns Go source for a precise go:embed list.
func Generate(config Config) ([]byte, error) {
	if config.Name == "" {
		return nil, fmt.Errorf("embed name is required")
	}
	if config.Package == "" {
		config.Package = "embed"
	}
	source := view.Dir(config.Root, config.Patterns...)
	files, err := view.Files(source)
	if err != nil {
		return nil, err
	}
	var buffer bytes.Buffer
	buffer.WriteString("package " + config.Package + "\n\n")
	buffer.WriteString("import \"embed\"\n\n")
	buffer.WriteString("// Code generated by runa. DO NOT EDIT.\n")
	for _, file := range files {
		path := filepath.ToSlash(filepath.Join(config.Root, file.Name))
		buffer.WriteString("//go:embed " + strings.TrimPrefix(path, "./") + "\n")
	}
	buffer.WriteString("var " + config.Name + " embed.FS\n")
	output, err := format.Source(buffer.Bytes())
	if err != nil {
		return nil, err
	}
	return output, nil
}
