package sanitize

import (
	"sync"

	"github.com/microcosm-cc/bluemonday"
)

// Policy sanitizes HTML.
type Policy interface {
	Sanitize(input string) string
}

type policyFunc func(string) string

func (fn policyFunc) Sanitize(input string) string {
	if fn == nil {
		return input
	}
	return fn(input)
}

var (
	registryMu sync.RWMutex
	registry   = map[string]Policy{}
)

func init() {
	Register("strict", Strict())
	Register("rich", RichText())
	Register("rich_text", RichText())
	Register("markdown", Markdown())
	Register("plain", PlainText())
	Register("plain_text", PlainText())
}

// Register registers a named policy.
func Register(name string, policy Policy) {
	if name == "" || policy == nil {
		return
	}
	registryMu.Lock()
	registry[name] = policy
	registryMu.Unlock()
}

// PolicyOf returns a named policy or Strict when missing.
func PolicyOf(name string) Policy {
	registryMu.RLock()
	policy := registry[name]
	registryMu.RUnlock()
	if policy == nil {
		return Strict()
	}
	return policy
}

// Use returns a named policy or Strict when missing.
func Use(name string) Policy { return PolicyOf(name) }

// Strict allows a small safe inline formatting subset.
func Strict() Policy {
	policy := bluemonday.StrictPolicy()
	policy.AllowElements("b", "strong", "i", "em", "u", "br", "p")
	return policy
}

// RichText allows common backend rich text HTML.
func RichText() Policy {
	return bluemonday.UGCPolicy()
}

// Markdown allows HTML commonly generated by Markdown renderers.
func Markdown() Policy {
	policy := bluemonday.UGCPolicy()
	policy.AllowAttrs("class").Matching(bluemonday.SpaceSeparatedTokens).OnElements("code", "pre")
	return policy
}

// PlainText strips all HTML tags.
func PlainText() Policy {
	return policyFunc(func(input string) string { return bluemonday.StrictPolicy().Sanitize(input) })
}
